# Generated by Django 2.2.19 on 2022-12-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_cliente_reuniao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codFunc', models.CharField(max_length=10, verbose_name='Código Funcionário')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('razaosocial', models.CharField(max_length=50, verbose_name='Razão social')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codFunc', models.CharField(max_length=10, verbose_name='Código Funcionário')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('funcao', models.CharField(max_length=20, verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='RelatoriodeRede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('descRede', models.TextField(max_length=500, verbose_name='Descrição de Rede')),
                ('numDispositivos', models.IntegerField(verbose_name='Dispositivos')),
                ('codFunc', models.CharField(max_length=10, verbose_name='Código Funcionário')),
                ('emailEmpresa', models.EmailField(max_length=30, verbose_name='Email Cliente')),
                ('firewall', models.CharField(max_length=20, verbose_name='Firewall')),
                ('antivirus', models.CharField(max_length=20, verbose_name='Antivírus')),
            ],
            options={
                'verbose_name': 'Relatório de Rede',
                'verbose_name_plural': 'Relatórios de Rede',
            },
        ),
        migrations.CreateModel(
            name='RelatorioFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codFunc', models.CharField(max_length=10, verbose_name='Código Funcionário')),
                ('cnpj', models.CharField(help_text='Formato XX.XXX.XXX-XXX', max_length=14, verbose_name='CNPJ')),
                ('emailEmpresa', models.EmailField(max_length=30, verbose_name='Email Cliente')),
                ('descPentest', models.CharField(max_length=500, verbose_name='Descrição do Pentest')),
            ],
            options={
                'verbose_name': 'Relatório Final',
                'verbose_name_plural': 'Relatórios Finais',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=10, verbose_name='Nível')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('valor', models.CharField(max_length=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='alunos',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.RenameField(
            model_name='reuniao',
            old_name='datar',
            new_name='data',
        ),
        migrations.AddField(
            model_name='reuniao',
            name='codFunc',
            field=models.CharField(default=1, max_length=10, verbose_name='Código Funcionário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(help_text='Formato XX.XXX.XXX-XXX', max_length=14, verbose_name='CNPJ'),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
