# Generated by Django 2.2.19 on 2022-12-06 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_auto_20221205_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriofinal',
            name='codFunc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Funcionario'),
        ),
    ]
