# Generated by Django 2.2.19 on 2022-12-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_auto_20221206_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='codFunc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Funcionario'),
        ),
        migrations.AlterField(
            model_name='relatorioderede',
            name='codFunc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Funcionario'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='codFunc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Funcionario'),
        ),
    ]
