# Generated by Django 2.2.19 on 2022-12-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_auto_20221206_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(default=1, max_length=40, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
