# Generated by Django 2.2.19 on 2022-12-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0009_auto_20221206_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
    ]
