# Generated by Django 2.2.19 on 2022-12-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0011_auto_20221206_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='relatorioderede',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='relatoriofinal',
            name='cnpj',
        ),
        migrations.AddField(
            model_name='relatorioderede',
            name='razaosocial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='aplic.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatoriofinal',
            name='razaosocial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reuniao',
            name='razaosocial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(help_text='Formato XX.XXX.XXX/XXXX-XX', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='razaosocial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.Cliente'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='E-mail do invite'),
        ),
    ]
